// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvonktzimhjlvmlofgal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2b25rdHppbWhqbHZtbG9mZ2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTMxNjIsImV4cCI6MjA2NTU2OTE2Mn0.408CXhEips8w7alnhX2lllf82TssMDHM4nTjeXkiXjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);